### ISSUE TITLE
Add support for k8s 1.18

### ISSUE THREAD

**Issue by jsanda** [datastax/cass-operator#111]
I tried running integration tests in a Kind cluster with version info as follows:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-dispatcher", GitCommit:"f2a77f678d6baccda27740d700f6cba2754dfacf", GitTreeState:"clean", BuildDate:"2020-04-21T04:44:03Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

I hit a validation error with the CRD that is due to the operator not yet supporting k8s 1.18:

```
STEP: creating a namespace
2020/06/09 10:01:19 exec: kubectl create namespace test-oss-test-all-the-things
namespace/test-oss-test-all-the-things created
2020/06/09 10:01:19 exec: helm install --namespace=test-oss-test-all-the-things --set image=datastax/cass-operator:latest cass-operator ../../charts/cass-operator-chart
Error: CustomResourceDefinition.apiextensions.k8s.io "cassandradatacenters.cassandra.datastax.com" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[podTemplateSpec].properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[podTemplateSpec].properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property]
```

**Comment by jimdickinson** [comment]
Some relevant info about why our CRD works in 1.17 but is broken in 1.18 is here https://github.com/operator-framework/operator-sdk/issues/3235

**Comment by kensipe** [comment]
@jimdickinson @jsanda FYI.... this issue is an issue in k8s with the introduction of validation in 1.18 around `x-kubernetes-list-map-keys` detailed on this https://github.com/kubernetes-sigs/controller-tools/issues/444
We are seeing a number of operators fail in this way.   The discussion in the WG API Expression meeting today is that a solution is being worked on and it will be back-ported to 1.18.x.
Another thread to follow is: https://github.com/operator-framework/operator-sdk/issues/3235

**Comment by kensipe** [comment]
I should add that it looks like the assuming in this issue is that cass-operator doesn't support 1.18 when it is a change in 1.18 that is the issue.   The worth around fix is to provide a default for protocol which will work... but this is a code generated file... it will break every time the code is re-generated :(

**Comment by jimdickinson** [comment]
Thanks @kensipe for following the link back to us! I think we worked around this well enough for now that I'm closing the issue. Hopefully the code generator improves for targeting more than one version of k8s with Operator SDK going to the CNCF.

**Comment by BostjanBozic** [comment]
Is there a plan to push this to certified-operators? Since if you are deploying this on OpenShift, it is still using v1.2.0 and is blocking deployment of operator.

**Comment by bradfordcp** [comment]
Yes, we are working through this issue now.
