### ISSUE TITLE
Question about sub resources created by the Operator

### ISSUE THREAD

**Issue by devdattakulkarni** [datastax/cass-operator#168]
I am looking to understand what all sub resources are created by the Operator when creating an instance of CassandraDatacenter.

I have briefly looked through the code for this information and think following is the list: Secret, StatefulSet, PersistentVolumeClaim, Service

Is this accurate?

If so, I wanted to double check if the implementation is correctly setting ownerReferences for PersistentVolumeClaim and Secret. The reason I ask this is because, when I tried to discover the connectivity graph for an instance of CassandraDatacenter through our kubectl connections plugin, the o/p did not include Secret and PersistentVolumeClaim in the results. 

See https://github.com/cloud-ark/kubeplus/blob/master/examples/datastax-dse/dse-connections-op.png 

This could be bug in kubectl connections implementation, but I doubt it as there are other Operators and Custom Resources that create these resources (PersistentVolumeClaim and Secret) which show up correctly in the kubectl connections o/p. So wanted to check if the ownerReferences for PersistentVolumeClaim and Secret are correctly being set or not.

**Comment by devdattakulkarni** [comment]
I can confirm that ownerReferences are not being set for PersistentVolumeClaim and Secret objects.
Here are outputs for PVC, Secret and StatefulSet (included for comparison).

PVC: https://gist.github.com/devdattakulkarni/8485f30f0905a40feb31f4e07532109e
Secret: https://gist.github.com/devdattakulkarni/87cb0ffce8e79df47a2a1c37f5f8d120
StatefulSet: https://gist.github.com/devdattakulkarni/55ee804cac6c5725326b75e682e09683

**Comment by devdattakulkarni** [comment]
I do see that the Secret has following annotation: 
"cassandra.datastax.com/watched-by": "[\"default/dc1\"]"

And PVC has following label:
"cassandra.datastax.com/datacenter": "dc1"

Is the intention that these are the only ways to encode the relationships between an instance of CassandraDatacenter and Secret and PVC?

**Comment by devdattakulkarni** [comment]
When CassandraDatacenter resource is created, in the describe o/p following events are seen:

Events:
  Type    Reason               Age                  From           Message
  ----    ------               ----                 ----           -------
  Normal  CreatedResource      3m50s                cass-operator  Created service cluster1-dc1-service
  Normal  CreatedResource      3m50s                cass-operator  Created service cluster1-seed-service
  Normal  CreatedResource      3m50s                cass-operator  Created service cluster1-dc1-all-pods-service
  Normal  CreatedResource      3m50s                cass-operator  Created statefulset cluster1-dc1-default-sts
  Normal  ScalingUpRack        3m50s                cass-operator  Scaling up rack default
  Normal  LabeledPodAsSeed     3m11s                cass-operator  Labeled pod a seed node cluster1-dc1-default-sts-0
  Normal  StartingCassandra    3m6s                 cass-operator  Starting Cassandra for pod cluster1-dc1-default-sts-0
  Normal  StartedCassandra     116s                 cass-operator  Started Cassandra for pod cluster1-dc1-default-sts-0
  Normal  CreatedResource      116s                 cass-operator  Created PodDisruptionBudget dc1-pdb
  Normal  LabeledRackResource  116s                 cass-operator  Update rack labels for PersistentVolumeClaim server-data-cluster1-dc1-default-sts-0
  Normal  CreatedUsers         114s (x4 over 115s)  cass-operator  Created users
  Normal  CreatedSuperuser     114s (x4 over 115s)  cass-operator  Created superuser

Here the only event related to PersistentVolumeClaim is that the rack label has been updated. So is it the case that PVC is already created independent of creation of CDC instance? If that is the case then deleting the CDC instance should not delete PVC. But the behavior that I am observing is that PVC gets deleted when CDC instance is deleted. Given this I would recommend adding ownerReference to PVC and also generating the PVC creation event from the Operator when a CDC instance is created.

**Comment by devdattakulkarni** [comment]
Also, looking at above events the 'CreatedSuperuser' event is the one that probably corresponds to the Superuser Secret object. Since the Operator is creating it as part of instantiating a CDC instance, I would recommend adding ownerReference to the Secret object. Doing so will correctly lead to its garbage collection when CDC instance is deleted (https://github.com/datastax/cass-operator/issues/171).

**Comment by johntrimble** [comment]
I believe the lack of an owner reference for the PVC is a bug. However, not cleaning up secrets upon deletion of the CassandraDatacenter was a design decision, which is why it does not have an owner reference set. The `"cassandra.datastax.com/watched-by": "["default/dc1"]"` annotation allows us to map changes to a secret back to the appropriate datacenter, since we don't set the owner reference. This is especially important in the cases where we did not generate the secret, but rather the user supplied us with secret.

**Comment by johntrimble** [comment]
Thinking about the PVCs, those are actually created by the statefulset. As to whether the PVC should be deleted automatically, this conversation is relevant: https://github.com/kubernetes/kubernetes/issues/55045

Setting automatic deletion aside, is there a reason the CassandraDatacenter should be an owner of the PVCs?

**Comment by devdattakulkarni** [comment]
Fair point that if PVC is created by the Statefulset then CassandraDatacenter should not be its owner. But in that case wouldn't it make sense to add the SSet as owner of the PVC instance? Right now no ownerReferences are set on the PVC instance. This though does not seem to cause issues with its garbage collection when CDC instance is deleted. The PVC gets deleted correctly.

**Comment by johntrimble** [comment]
Looking back through our code, it does look like we specifically delete the PVC when the CDC instance is deleted:

https://github.com/datastax/cass-operator/blob/394d25a6d6ec452ecd1667f3dca40b7496379eea/operator/pkg/reconciliation/reconcile_datacenter.go#L37-L40

As to why the PVCs do not have an owner reference to the statefulset, that I think is about the implementation of statefulsets. They might not set the owner reference in order to avoid a cascade delete of the PVCs when the statefulset is deleted.

Since we are deleting the PVCs anyway, I think you could argue that we should make the CDC an owner of the PVCs. However, we'd then have to watch for changes to PVCs so that reconcile is called when they are created. Also, I don't think we'd get out of needing the explicit code to delete the PVCs as the CDC might get deleted before the owner reference is set. I could be wrong, but I don't think setting the owner reference gets us anything in this case.

**Comment by johntrimble** [comment]
I think everything here has been answered. Please reopen if needed.
