### ISSUE TITLE
podTemplate option to include additional containers in the pod

### ISSUE THREAD

**Issue by sandeepnethi** [datastax/cass-operator#199]
Hi,

I couldn't find any instructions on how to add additional containers with "CassandraDatacenter" kind. Is there a way to integrate additional containers along with cassandra container in each pod? 

The idea behind this question is to add sidecar container to configure reaper and also to schedule backups. 

Let me know any clarifications is needed. 

Thanks in advance.

**Comment by jimdickinson** [comment]
Hey @sandeepnethi - We've exposed the ability for you to provide `podTemplateSpec` inside the `spec` field of the `CassandraDatacenter`. We've got Reaper integration underway, so you should probably use that instead of rolling your own. I'm realizing that our docs don't make this subject very clear, so we'll get that fixed. Let me know if you need more specific advice!

**Comment by jimdickinson** [comment]
Fixed by #263
