### ISSUE TITLE
Refactor how CRD is generated in Helm

### ISSUE THREAD

**Issue by bradfordcp** [datastax/cass-operator#295]
Right now users must select the appropriate YAML file to install cass-operator related to their version of Kubernetes. This is due to a BUG upstream, but it leads to additional work on our side maintaining these templates and rendering multiple CRDs. Instead let's remove the offending entries (or provide the appropriate default) and consolidate the CRDs into a single file that works across versions.

**Comment by jsanda** [comment]
I want fill in some details around the Helm problems that this is causing. I am trying to include the cass-operator chart as a subchart for another project. I tried installing the cass-operator chart in a cluster that already has the CRD installed. The `helm chart install` failed with:

`Error: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "cassandradatacenters.cassandra.datastax.com" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "test": current value is "cass-operator"; annotation validation error: key "meta.helm.sh/release-namespace" must equal "k8c19": current value is "test-canary-upgrade"`

In Helm 3, CRDs are treated separately from other objects and need to be stored in the `crds` directory of the chart. Unfortunately simply moving `templates/customresourcedefinition.yaml` to a `charts` directory did not work because the file uses templates. Helm 3 does not allow template in CRDs. 

Fixing this issue will hopefully🤞  remove the need for templates in `customresourcedefinition.yaml`, and then we can move it over to the `crds` directory.
