### ISSUE TITLE
Cassandra Datacenter deletion hangs on finalizer

### ISSUE THREAD

**Issue by mgorsk1** [datastax/cass-operator#357]
When helm delete command is executed to delete helm deployment containing cassandra datacenter (and operator), cassandra data center resource is not deleted. Doing `kubectl delete cassdc $name_of_cassdc_object` doesn't do any good either - the command hangs indefinitely and object is not removed. Using `grace-period=0` and `force` flags also doesn't help - command terminates immediately but the object is still there.

Workaround is to do `kubectl edit cassdc $name_of_cassdc_object` and delete lines presented at screenshot. After that action object disappears.
![image](https://user-images.githubusercontent.com/5680655/104894208-af79b700-5974-11eb-9992-2719bfb51985.png)

We're using latest version of CRD and Cassandra operator (`1.5.0`) on kubernetes `1.19.4`

**Comment by jimdickinson** [comment]
@jsanda is this related to how K8ssandra installs things with helm? The cassdc needs to be explicitly deleted, and then the operator can reconcile that change and do some cleanup on other resources (namely PVCs) and then it removes the finalizer.

The deletion procedure is outlined in the README.

https://github.com/datastax/cass-operator#uninstall

**Comment by jsanda** [comment]
@mgorsk1 did you hit this with k8ssandra? If so, what version of the charts?

The problem is that there are no ordering guarantees when you delete with Helm. The cass-operator deployment can get deleted before the CassandraDatacenter, and then you end up in this situation. 

In k8ssandra we implemented a pre-delete hook that will make sure any CassandraDatacenters created via the k8ssandra chart get deleted before the cass-operator deployment. This functionality was introduced in version 0.24.0 of the k8ssandra chart.

**Comment by mgorsk1** [comment]
Thanks for replies ! We are using our own chart, installing operator and cassandra datacenter. Something much simpler than k8ssandra. We'll try adding the pre-delete job similar to the cleaner one, thanks for the tip !

**Comment by mgorsk1** [comment]
Just to update - added a pre-delete job and worked like a charm, thanks for the help !
