### ISSUE TITLE
Run cassandra pods as nonRootUser

### ISSUE THREAD

**Issue by joe-sch** [datastax/cass-operator#66]
It should be possible to define a different user than root in a  cassandradatacenter.

When i exec into a cassandra pod, i see that the pod is executed as root user.
But many k8s clusters have a policy which do not allow to run an image as root user.
In the crd definition i can't find an option to define a securityContext for the pods.

**Comment by jimdickinson** [comment]
Do you have a cassandra docker image you've used previously that doesn't come up as root? I spent quite a bit of time looking at this because it's one of the few differences in the API for us to bring up DSE pods vs. Cassandra pods. The upstream images from https://github.com/docker-library/cassandra do start as root, and then they drop to a cassanda user using gosu just before Java starts. ([link](https://github.com/docker-library/cassandra/blob/f6829f33cac880b0f0787b223d3a8b19f82efab5/docker-entrypoint.sh#L14))

We intend for users to use cassandra images from https://github.com/datastax/management-api-for-apache-cassandra and we based our image on , but we do want to support anyone forking that and making minimal changes, like removing the possibility of using the root user. Let us know more about your configuration / requirements and we'll make an update to unblock you!

cc @eldondevat @tjake

**Comment by joe-sch** [comment]
Yes we have cassandra running in a dev environment (production is planned for autumn), 
Our statefulset is based on this example: https://kubernetes.io/docs/tutorials/stateful-application/cassandra/. But we added a `securityContext` to run the cassandra pods as user 999.
The user and group with id 999 is built in: https://github.com/docker-library/cassandra/blob/master/3.11/Dockerfile 

````
securityContext:
        runAsUser: 999
````

This is ok for us and help us to run on our on prem kubernetes envirenment.
However, it would be ideal if the user could choose freely, as described by [this guide](https://docs.openshift.com/container-platform/4.1/openshift_images/create-images.html) `SUPPORT ARBITRARY USER IDS`
